ToDoListApp/Controllers/BaseMediatrController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace ToDoListApp.Controllers
{
    public abstract class BaseMediatrController : Controller
    {
        private IMediator _mediator;
        public IMediator Mediator => _mediator ?? (_mediator = HttpContext.RequestServices.GetService<IMediator>());
    }
}

ToDoListApp/Controllers/ToDoListController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoListApp.Application.ToDoItems.Commands.AddToDoItem;
using ToDoListApp.Application.ToDoItems.Commands.DeleteToDoItem;
using ToDoListApp.Application.ToDoItems.Commands.ToggleDone;
using ToDoListApp.Application.ToDoItems.Commands.UpdateToDoItem;
using ToDoListApp.Application.ToDoItems.Queries;
using ToDoListApp.Application.ToDoItems.Queries.GetToDoItem;
using ToDoListApp.Domain.Entities;
using X.PagedList;

namespace ToDoListApp.Controllers
{
    public class ToDoListController : BaseMediatrController
    {

        public async Task<IActionResult> Items(int page = 1)
        {
            var items = await Mediator.Send(new GetAllToDoItemsQuery());
            var pagedItems = items.ToDoItems.ToPagedList(page, 6);
            ViewBag.ItemsPage = pagedItems;
            return View(items);
        }

        [HttpGet]
        public async Task<IActionResult> Items(GetAllToDoItemsQuery query, int page = 1)
        {
            var items = await Mediator.Send(query);
            var pagedItems = items.ToDoItems.ToPagedList(page, 6);
            ViewBag.ItemsPage = pagedItems;
            return View(items);
        }

        /*        [HttpGet]
                public async Task<IActionResult> Item(int itemId)
                {
                    var item = await Mediator.Send(new GetToDoItemQuery { ToDoItemId = itemId });
                    return View(item);
                }*/

        public async Task<IActionResult> Delete(int id)
        {
            await Mediator.Send(new DeleteToDoItemCommand { Id = id });
            return View("Items", await Mediator.Send(new GetAllToDoItemsQuery()));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateToDoItemCommand command)
        {
            if (ModelState.IsValid)
            {
                await Mediator.Send(command);
                return View("Items");
            }

            return View("Create", command);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var toDoItem = await Mediator.Send(new GetToDoItemQuery { ToDoItemId = id });
            return View(toDoItem);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, ToDoItem item)
        {
            item.ToDoItemId = id;
            await Mediator.Send(new UpdateToDoItemCommand { ToDoItem = item });
            return View("Items", await Mediator.Send(new GetAllToDoItemsQuery()));
        }

        [HttpPost]
        public async Task<IActionResult> ToggleDone(int id)
        {
            var newStatus = await Mediator.Send(new ToggleDoneCommand {ItemId = id});
            return Ok(newStatus);
        }
    }
}

ToDoListApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoListApp</title>



    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="ToDoList" asp-action="Items">ToDoListApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="Items">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="Create">Create new item</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - <a href="https://twitter.com/TotolotekPL/status/1084164870701019136" target="_blank">ToDoListApp</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
<script src="~/js/site.js" asp-append-version="true"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoListApp/Views/ToDoList/Create.cshtml
@using ToDoListApp.Domain.Enums
@model ToDoListApp.Application.ToDoItems.Commands.AddToDoItem.CreateToDoItemCommand
@{
    ViewData["Title"] = "Create";
}

<h1>Create a ToDo item</h1>
<form asp-controller="ToDoList" asp-action="Create" method="post" class="form-group">
    <div class="form-group row">
        <label asp-for="Title" class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
            <input asp-for="Title" class="form-control" />
        </div>
        <span asp-validation-for="Title" class="col-sm-6 col-form-label"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <span asp-validation-for="Description" class="col-sm-6 col-form-label"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Priority" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Priority" asp-items="Html.GetEnumSelectList<Priority>()" class="btn btn-primary dropdown-toggle form-inline"></select>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EstimatedFinish" class="col-sm-2 col-form-label">Estimated finish date</label>
        <div class="input-group col-sm-10 date">
            <input asp-for="EstimatedFinish" type="datetime" class="form-control datetimepicker-input" id="datetimepicker5" data-toggle="datetimepicker" data-target="#datetimepicker5" />
        </div>
        <span asp-validation-for="EstimatedFinish" class="col-sm-6 col-form-label"></span>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</form>

ToDoListApp/Views/ToDoList/Edit.cshtml
@using ToDoListApp.Domain.Enums
@model ToDoListApp.Domain.Entities.ToDoItem
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit ToDo item</h1>

<form asp-controller="ToDoList" asp-action="Edit" method="post" class="form-group">
    <div class="form-group row">
        <label asp-for="Title" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Title" value="@Model.Title" class="form-control" />
        </div>
        <span asp-validation-for="Title"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Description" value="@Model.Description" class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Priority" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Priority" asp-items="Html.GetEnumSelectList<Priority>()" class="btn btn-primary dropdown-toggle form-inline">
                <option selected="selected" value="@Model.Priority"></option>
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EstimatedFinish" class="col-sm-2 col-form-label">Estimated finish date</label>
        <div class="input-group col-sm-10 date">
            <input asp-for="EstimatedFinish" type="text" value="@Model.EstimatedFinish.ToString("G")" class="form-control datetimepicker-input" id="datetimepicker5" data-toggle="datetimepicker" data-target="#datetimepicker5"/>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Done" class="col-sm-2 form-check-label"></label>
        <div class="form-check">
            <input asp-for="Done" type="checkbox" value="@Model.Done" class="form-check-inline"/>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</form>

ToDoListApp/Views/ToDoList/Items.cshtml
@using X.PagedList.Mvc;
@using X.PagedList; 
@using ToDoListApp.Application.ToDoItems.Queries
@using X.PagedList.Mvc.Common
@using X.PagedList.Mvc.Core
@model ToDoListApp.Application.ToDoItems.Queries.ToDoItemsViewModel
@{
    ViewData["Title"] = "ToDoList";
}

<h1>ToDoList</h1>
<form asp-controller="ToDoList" asp-action="Items" method="get" class="form-group">
    <div class="form-group row">
        <div class="col-sm-3">
            <input asp-for="Query.SearchTitle" class="form-control" placeholder="Search for title" />
        </div>
        <div class="col-sm-3">
            <input asp-for="Query.SearchDescription" class="form-control" placeholder="Search for description" />
        </div>
        <div class="col-sm-3">
            <select asp-for="Query.DoneStatus" asp-items="Html.GetEnumSelectList<DoneStatus>()" class="btn btn-primary dropdown-toggle form-inline"></select>
            <input type="submit" value="Filter" class="btn btn-primary" />
        </div>
    </div>
</form>
<div>

    @foreach (var item in ViewBag.ItemsPage)
    {
        <div class="card mt-3">
            <div class="card-body">
                <h5 class="card-title">@item.Title</h5>
                <p class="card-text">@item.Description</p>
                <p class="card-text">Estimated finish time: @item.EstimatedFinish</p>

                <div class="card-footer">
                    <button data-item-id="@item.ToDoItemId" class="btn fa-check-square pull-right @(item.Done ? "btn-success fas js-toggle-uncheck" : "btn-secondary far js-toggle-check")"></button>
                    <a asp-controller="ToDoList" asp-action="Edit" method="get" asp-route-id="@item.ToDoItemId" class="btn btn-info fa fa-edit"></a>
                    <a asp-controller="ToDoList" asp-action="Delete" asp-route-id="@item.ToDoItemId" class="btn btn-danger fa fa-trash"></a>
                </div>
            </div>
        </div>
    }
    
    @Html.PagedListPager((IPagedList)ViewBag.ItemsPage, page => Url.Action("Items", new { page, Model.Query.DoneStatus }),
        new PagedListRenderOptions {
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" }})

</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $(".js-toggle-check").click(function (e) {
                var button = $(e.target);
                $.post("/todolist/toggledone/", { id: button.attr("data-item-id") })
                    .done(function () {
                        button
                            .removeClass("js-toggle-check")
                            .addClass("js-toggle-uncheck")
                            .removeClass("far")
                            .addClass("btn-success")
                            .addClass("fas");
                        location.reload();
                    })
                    .fail(function () {
                        alert("Something failed!");
                    });
            });
            $(".js-toggle-uncheck").click(function (e) {
                var button = $(e.target);
                $.post("/todolist/toggledone/", { id: button.attr("data-item-id") })
                    .done(function () {
                        button
                            .removeClass("js-toggle-uncheck")
                            .addClass("js-toggle-check")
                            .removeClass("fas")
                            .addClass("far")
                            .removeClass("btn-success");
                        location.reload();
                    })
                    .fail(function () {
                        alert("Something failed!");
                    });
            });
        });
    </script>
}